t0:
  - 宝洁
  - 联合利华
  - 欧莱雅
  - 玛氏
  - 雅诗兰黛

t1:
  - 亿滋
  - 雀巢
  - 强生
  - 百胜
  - LVMH
  - 耐克
  - 可口可乐
  - 达能
  - 资生堂
  - 高露洁
  - 金佰利
  - 默克

shanghai_picks:
  - Wayfair
  - 索尼
  - 宜家
  - 乐高
  - 爱立信
  - 沃尔沃
